In [1]:
from sklearn import svm,datasets
iris=datasets.load_iris()

In [3]:
import pandas as pd
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['flower']=iris.target
df['flower']=df['flower'].apply(lambda x:iris.target_names[x])
df[47:52]

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),flower
47,4.6,3.2,1.4,0.2,setosa
48,5.3,3.7,1.5,0.2,setosa
49,5.0,3.3,1.4,0.2,setosa
50,7.0,3.2,4.7,1.4,versicolor
51,6.4,3.2,4.5,1.5,versicolor

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(iris.target,iris.target,test_size=0.3)

In [9]:
model = svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(x_train,y_train)

ValueError: Expected 2D array, got 1D array instead:
array=[0. 1. 0. 0. 1. 2. 0. 2. 0. 0. 2. 1. 2. 2. 0. 1. 0. 0. 0. 0. 1. 1. 2. 0.
 2. 1. 1. 1. 1. 2. 1. 1. 1. 2. 1. 2. 0. 2. 2. 0. 2. 1. 0. 0. 2. 0. 0. 0.
 1. 1. 1. 1. 1. 2. 0. 1. 1. 1. 1. 1. 0. 0. 2. 0. 0. 2. 2. 2. 0. 0. 2. 2.
 1. 0. 1. 0. 1. 1. 1. 1. 2. 0. 0. 2. 1. 1. 0. 2. 0. 2. 1. 1. 2. 0. 1. 0.
 2. 2. 0. 2. 2. 1. 2. 2. 0.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [11]:
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [12]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [13]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [15]:
import numpy as np
kernels=['rbf','linear']
c=[1,10,20]
avg_scores={}
for kval in kernels:
    for cval in c:
        cv_score=cross_val_score(svm.SVC(kernel=kval,C=cval,gamma='auto'),iris.data,iris.target,cv=5)
        avg_scores[kval+'-'+str(cval)]=np.average(cv_score)

avg_scores

{'rbf-1': np.float64(0.9800000000000001),
 'rbf-10': np.float64(0.9800000000000001),
 'rbf-20': np.float64(0.9666666666666668),
 'linear-1': np.float64(0.9800000000000001),
 'linear-10': np.float64(0.9733333333333334),
 'linear-20': np.float64(0.9666666666666666)}

In [16]:
#Grid Search CV
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
     'kernel':['rbf','linear']
},cv=5,return_train_score=False)
clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.000843  , 0.000385  , 0.00037355, 0.00031877, 0.00033517,
        0.00029573]),
 'std_fit_time': array([3.59878370e-04, 4.77631384e-05, 1.06788105e-05, 2.18102835e-05,
        8.15851517e-06, 1.64066633e-05]),
 'mean_score_time': array([0.00043602, 0.00023017, 0.00023041, 0.00019879, 0.0002079 ,
        0.00018115]),
 'std_score_time': array([1.22601445e-04, 2.18579782e-05, 4.34576316e-06, 6.62340373e-06,
        5.51978917e-06, 7.48254595e-06]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],
 'split0_test_score': array([0.96666667, 0.96666667, 0.96666667, 1.        , 0.96666667,
        1.        ]),
 'split1_test_score': array([1., 1., 1., 1., 1., 1.]),
 'split2_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.9       , 0.9       ,
        0.9       ]),
 'split3_test_score': array([0.96666667, 0.96666667, 0.96666667, 0.96666667, 0.96666667,
        0.93333333]),
 'split4_test_score': array([1., 1., 1., 1., 1., 1.]),
 'mean_test_score': array([0.98      , 0.98      , 0.98      , 0.97333333, 0.96666667,
        0.96666667]),
 'std_test_score': array([0.01632993, 0.01632993, 0.01632993, 0.03887301, 0.03651484,
        0.0421637 ]),
 'rank_test_score': array([1, 1, 1, 4, 5, 6], dtype=int32)}

In [18]:
df=pd.DataFrame(clf.cv_results_)
df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000843,0.000360,0.000436,0.000123,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
1,0.000385,0.000048,0.000230,0.000022,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
2,0.000374,0.000011,0.000230,0.000004,10,rbf,"{'C': 10, 'kernel': 'rbf'}",0.966667,1.0,0.966667,0.966667,1.0,0.980000,0.016330,1
3,0.000319,0.000022,0.000199,0.000007,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.966667,1.0,0.973333,0.038873,4
4,0.000335,0.000008,0.000208,0.000006,20,rbf,"{'C': 20, 'kernel': 'rbf'}",0.966667,1.0,0.900000,0.966667,1.0,0.966667,0.036515,5
5,0.000296,0.000016,0.000181,0.000007,20,linear,"{'C': 20, 'kernel': 'linear'}",1.000000,1.0,0.900000,0.933333,1.0,0.966667,0.042164,6

In [19]:
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier

In [ ]:
model_parms={
    'svm':{
        'model':svm.SVC(gamma='auto'),
        'params':{

        }
    },
    'random_forest':{

    },
    'logistic_regression':{
        'model':
    }
}